/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface AppRoot {}
  interface CountryItaly {}
  interface CountrySrilanka {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCountryItalyElement extends Components.CountryItaly, HTMLStencilElement {}
  var HTMLCountryItalyElement: {
    prototype: HTMLCountryItalyElement;
    new (): HTMLCountryItalyElement;
  };

  interface HTMLCountrySrilankaElement extends Components.CountrySrilanka, HTMLStencilElement {}
  var HTMLCountrySrilankaElement: {
    prototype: HTMLCountrySrilankaElement;
    new (): HTMLCountrySrilankaElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'country-italy': HTMLCountryItalyElement;
    'country-srilanka': HTMLCountrySrilankaElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppRoot {}
  interface CountryItaly {}
  interface CountrySrilanka {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'country-italy': CountryItaly;
    'country-srilanka': CountrySrilanka;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'country-italy': LocalJSX.CountryItaly & JSXBase.HTMLAttributes<HTMLCountryItalyElement>;
      'country-srilanka': LocalJSX.CountrySrilanka & JSXBase.HTMLAttributes<HTMLCountrySrilankaElement>;
    }
  }
}


